package br.unioeste.jgoose.view;

import br.unioeste.jgoose.controller.Controller;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author Diego Peliser
 */
public class CasosDeUsoView extends javax.swing.JFrame {

    private MainView principal = new MainView();

    /**
     * Creates new form CasosDeUsoView
     */
    public CasosDeUsoView(MainView interfacePrincipal) {
        initComponents();
        setLocationRelativeTo(null);
        principal = interfacePrincipal;
        atualizaTabela();

    }

    /*
     * Método que atualiza a Tabela de Casos de Uso
     */
    private void atualizaTabela() {
        DefaultTableModel tabCasosDeUso = new DefaultTableModel();
        tabCasosDeUso.addColumn("ID");
        tabCasosDeUso.addColumn("Ator");
        tabCasosDeUso.addColumn("Caso de Uso");
        tabCasosDeUso.addColumn("Tipo");
        String vetCasosDeUso[] = new String[4];
        // adiciona os dados dos casos de uso no modelo da tabela
        for (int i = 0; i < Controller.getCasosDeUso().size(); i++) {
            vetCasosDeUso[0] = "" + i;
            vetCasosDeUso[1] = Controller.getCasosDeUso().get(i).getAtor();
            vetCasosDeUso[2] = Controller.getCasosDeUso().get(i).getName();
            vetCasosDeUso[3] = Controller.getCasosDeUso().get(i).getTipo();
            tabCasosDeUso.addRow(vetCasosDeUso);
        }
        tabelaCasosDeUso.setModel(tabCasosDeUso);
        // seta a largura das colunas da tabela
        tabelaCasosDeUso.getColumnModel().getColumn(0).setPreferredWidth(30);
        tabelaCasosDeUso.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabelaCasosDeUso.getColumnModel().getColumn(2).setPreferredWidth(300);
        tabelaCasosDeUso.getColumnModel().getColumn(3).setPreferredWidth(200);
    }

    /*
     * Método que insere um texto na área de texto de Casos de Uso com formatação
     */
    private void insertStyle(String texto, SimpleAttributeSet estilo) {
        Document doc = textoCasosDeUso.getStyledDocument();
        try {
            doc.insertString(doc.getLength(), texto, estilo);
        } catch (BadLocationException ex) {
            Logger.getLogger(CasosDeUsoView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CasosDeUsoMapeados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCasosDeUso = new javax.swing.JTable(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        CasosDeUsoMapeados1 = new javax.swing.JLabel();
        salvarDescricao = new javax.swing.JButton();
        exibirNFRs = new javax.swing.JButton();
        exibirHerancas = new javax.swing.JButton();
        diagrama = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        textoCasosDeUso = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Casos de Uso");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        CasosDeUsoMapeados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CasosDeUsoMapeados.setText("Casos de Uso Mapeados");

        tabelaCasosDeUso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Ator", "Caso de Uso", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCasosDeUso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCasosDeUsoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaCasosDeUso);
        tabelaCasosDeUso.getColumnModel().getColumn(0).setResizable(false);
        tabelaCasosDeUso.getColumnModel().getColumn(1).setResizable(false);
        tabelaCasosDeUso.getColumnModel().getColumn(2).setResizable(false);
        tabelaCasosDeUso.getColumnModel().getColumn(3).setResizable(false);

        CasosDeUsoMapeados1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CasosDeUsoMapeados1.setText("Especificações dos Casos de Uso");

        salvarDescricao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unioeste/JGOOSE/view/6228_16x16.png"))); // NOI18N
        salvarDescricao.setText("Salvar Descrição");

        exibirNFRs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unioeste/JGOOSE/view/8498_16x16.png"))); // NOI18N
        exibirNFRs.setText("Exibir NFRs");

        exibirHerancas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unioeste/JGOOSE/view/8498_16x16.png"))); // NOI18N
        exibirHerancas.setText("Exibir Heranças (ISA)");

        diagrama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unioeste/JGOOSE/view/6697_16x16.png"))); // NOI18N
        diagrama.setText("Diagrama");

        textoCasosDeUso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane3.setViewportView(textoCasosDeUso);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CasosDeUsoMapeados))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(salvarDescricao)
                        .addGap(18, 18, 18)
                        .addComponent(exibirNFRs)
                        .addGap(18, 18, 18)
                        .addComponent(exibirHerancas)
                        .addGap(18, 18, 18)
                        .addComponent(diagrama)))
                .addGap(0, 17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(CasosDeUsoMapeados1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {diagrama, exibirHerancas, exibirNFRs, salvarDescricao});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(CasosDeUsoMapeados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CasosDeUsoMapeados1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarDescricao)
                    .addComponent(exibirNFRs)
                    .addComponent(exibirHerancas)
                    .addComponent(diagrama))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        principal.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void tabelaCasosDeUsoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCasosDeUsoMouseClicked
        int n = tabelaCasosDeUso.getSelectedRow(); // pega a linha selecionada
        textoCasosDeUso.setText(""); // limpa o painel de texto
        // define o objeto com formatação negrito negrito
        SimpleAttributeSet negrito = new SimpleAttributeSet();
        StyleConstants.setBold(negrito, true);
        //StyleConstants.setForeground(setNegrito, Color.RED); 
        //serve para definir uma cor ao texto tb.. (nao serve para sua dúvida.. m
        //as vale pro futuro se precisar. Nesse caso, a cor ficaria com a cor VERMELHA) 

        // insere os dados do caso de uso selecionado
        insertStyle("Caso de Uso: " + Controller.getCasosDeUso().get(n).getName() + "\n", null);
        insertStyle("INFORMAÇÃO CARACTERÍSTICA:\n", negrito);
        insertStyle("Objetivo no Contexto:\n", null);
        insertStyle("Escopo:\n", null);
        insertStyle("Pré-Condições:\n", null);
        insertStyle("Condição Final de Sucesso:\n", null);
        insertStyle("Condição Final de Falha:\n", null);
        insertStyle("Ator Primário: " + Controller.getCasosDeUso().get(n).getAtor() + "\n", null);
        insertStyle("CENÁRIO PRINCIPAL(Primary Scenario):\n", negrito);
        insertStyle("	1. Descrição Passo 1 [<<include>> opcional]\n", null);
        insertStyle("	2. Descrição Passo 2 [<<include>> opcional]\n", null);
        insertStyle("	3. Descrição Passo 3 [<<include>> opcional]\n", null);
        insertStyle("	4. Descrição Passo 4 [<<include>> opcional]\n", null);
        insertStyle("EXTENSÕES (Extends):\n", negrito);
        insertStyle("	2.1. Extensão Passo 2 <<extend>>\n", null);
        insertStyle("	2.2. Extensão Passo 2 <<extend>>\n", null);
        insertStyle("	3.1. Extensão Passo 3 <<extend>>\n", null);
        insertStyle("Requisitos Especiais (Special Requirements):\n", negrito);
        insertStyle("	NFR 1: Requisito Não Funcional <<softgoal>>\n", null);
    }//GEN-LAST:event_tabelaCasosDeUsoMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CasosDeUsoMapeados;
    private javax.swing.JLabel CasosDeUsoMapeados1;
    private javax.swing.JButton diagrama;
    private javax.swing.JButton exibirHerancas;
    private javax.swing.JButton exibirNFRs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton salvarDescricao;
    private javax.swing.JTable tabelaCasosDeUso;
    private javax.swing.JTextPane textoCasosDeUso;
    // End of variables declaration//GEN-END:variables
}
